// packages/simm-player/packages/react/src/App.tsx
import React, { useEffect, useState } from "react";
import { initializePlayer, playVideo, getVideoInfo } from "@simm-player/core";
export const VideoPlayer = () => {
  const [videoInfo, setVideoInfo] = useState<any>(null);

  useEffect(() => {
    initializePlayer();
    setVideoInfo(getVideoInfo());
  }, []);

  return (
    <div>
      <h2>Video Player</h2>
      {videoInfo && (
        <div>
          <p>Title: {videoInfo.title}</p>
          <p>Duration: {videoInfo.duration}</p>
          <p>Resolution: {videoInfo.resolution}</p>
        </div>
      )}
      <button onClick={playVideo}>Play</button>
    </div>
  );
};

export default VideoPlayer;

// packages/simm-player/packages/vue/src/App.vue
<template>
  <header></header>

  <main>
    <div>
      <h2>Video Player</h2>
      <div v-if="videoInfo">
        <p>Title: {{ videoInfo.title }}</p>
        <p>Duration: {{ videoInfo.duration }}</p>
        <p>Resolution: {{ videoInfo.resolution }}</p>
      </div>
      <button
        @click="
          {
            playVideo;
          }
        "
      >
        Play
      </button>
    </div>
  </main>
</template>

<script setup lang="ts">
import { initializePlayer, playVideo, getVideoInfo } from "@simm-player/core";
import { onMounted, ref } from "vue";

const videoInfo = ref(getVideoInfo());

onMounted(() => {
  initializePlayer();
});
</script>
<style scoped></style>
